### ISSUE TITLE
NSFW.mlmodel: unable to read document

### ISSUE THREAD

**Issue by DineshKachhot** [lovoo/NSFWDetector#10]
I am trying to implement it in my demo app.
Imported using pod file and written the simple code given in readme file. While build the app getting the following error:

CoreML Model Compiler Error Group
PathTo/NSFW.mlmodel: unable to read document

There was an problem decoding this CoreML document
validator error: Model did not specify a valid model-parameter type.

I tried using `pip install coremltools==2.0b1` as per [this](https://github.com/apple/coremltools/issues/195) post, but it's not working for me.

**Comment by absolute-heike** [comment]
Sounds like the Xcode 9 issue. Models created with CreateML only work with Xcode 10. I should definitely put that in the README 😯

**Comment by DineshKachhot** [comment]
Yah I see, It's working in Xcode 10, thanks.
