### ISSUE TITLE
How is it open source if there is no training data set ?

### ISSUE THREAD

**Issue by onmyway133** [lovoo/NSFWDetector#16]
For science  👨‍🔬 👩‍🔬

**Comment by absolute-heike** [comment]
Oh sure, looks like you are interested in a couple of hundred dick pics! If so, I'll gladly send you the training set. 😈😜

**Comment by GarrickLin** [comment]
hate you guys' work!

**Comment by absolute-heike** [comment]
Hey, seems like a lot of people are really interested in the dataset.

I am trying to figure out a way to share the dataset without getting into any legal issues :)

**Comment by genghisun** [comment]
Hi! I've just started doing research in this area recently, have you shared the dataset yet?
