### ISSUE TITLE
Error in NSFW.mlmodel

### ISSUE THREAD

**Issue by davidseek** [lovoo/NSFWDetector#9]
Downloaded the Repo to checkout the example project.
Executed `pod install`, Using Version 9.4.1 (9F2000), I get:

<img width="998" alt="nsfw" src="https://user-images.githubusercontent.com/17073950/45600553-5d46b680-b9b3-11e8-8ecd-2f7a6d546c21.png">

**Comment by davidseek** [comment]
I assume right now that this is a Xcode 9 issue.
Testing it with Xcode 10 beta now.

**Comment by absolute-heike** [comment]
Oh thank you! Yes this is correct. CreateML is only available in Xcode 10 and above 😊

Should work fine with Xcode 10

**Comment by davidseek** [comment]
Yes I can confirm that. 
I have just downloaded `Version 10.0 (10A254a)`.
Wanted to wait for official release but it's worth it 👍
